name: C/C++ CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make test-build-only
    - name: Run tests
      run: ./test/dtest/dtest-cxx17 test/build
    - name: Dump results
      run: cat dtest.log.json
