name: C/C++ CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make test-build-only

    - name: Run tests
      run: |
        export LD_LIBRARY_PATH=lib/*
        echo $LD_LIBRARY_PATH
        ./test/dtest/dtest-cxx17 test/build

    - name: Dump results
      if: ${{ always() }}
      run: cat dtest.log.json
