name: test

on: [ push, pull_request ]

jobs:

  test-ubuntu-latest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: make test-build-only

    - name: Run tests
      run: |
        export LD_LIBRARY_PATH=$(realpath lib/*)
        ./test/dtest/dtest-cxx11 test/build

    - name: Dump results
      if: ${{ always() }}
      run: cat dtest.log.json


  test-ubuntu-22:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: make test-build-only

    - name: Run tests
      run: |
        export LD_LIBRARY_PATH=$(realpath lib/*)
        ./test/dtest/dtest-cxx11 test/build

    - name: Dump results
      if: ${{ always() }}
      run: cat dtest.log.json
  
  
  test-ubuntu-20:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: make test-build-only

    - name: Run tests
      run: |
        export LD_LIBRARY_PATH=$(realpath lib/*)
        ./test/dtest/dtest-cxx11 test/build

    - name: Dump results
      if: ${{ always() }}
      run: cat dtest.log.json


  test-ubuntu-18:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3

    - name: Build
      run: make test-build-only

    - name: Run tests
      run: |
        export LD_LIBRARY_PATH=$(realpath lib/*)
        ./test/dtest/dtest-cxx11 test/build

    - name: Dump results
      if: ${{ always() }}
      run: cat dtest.log.json
